# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nth', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('no1', models.IntegerField()),
                ('no2', models.IntegerField()),
                ('no3', models.IntegerField()),
                ('no4', models.IntegerField()),
                ('no5', models.IntegerField()),
                ('no6', models.IntegerField()),
                ('nob', models.IntegerField()),
                ('winmoney', models.IntegerField()),
                ('winco', models.IntegerField()),
            ],
        ),
    ]
